[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "sinapse-sdk"
version = "0.1.0"
description = "SINAPSE SDK — curated software components for AI-coupled HPC workflows"
dependencies = [
    "rhapsody-py>=0.5.0",
    "radical.asyncflow>=0.5.0",
    "quacc",
    "rootstock",
]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.9"
authors = [
    {name = "The SINAPSE project"}
]

[project.urls]
Homepage = "http://project-sinapse.org"
Repository = "https://github.com/SINAPSE-NSF/sinapse-sdk"
